# Generated by Django 5.0.6 on 2024-07-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='session_id',
        ),
    ]
